Primitive query params
googleapis/gapic-generator-java pull request #1023
Opened 2022-08-02 15:12 UTC by diego92sigma6

2022-08-02 22:07 UTC, blakeli0 approved these changes

2022-08-23 18:13 UTC, blakeli0 commented on src/main/java/com/google/api/generator/gapic/composer/rest/HttpJsonServiceStubClassComposer.java
> +import com.google.api.generator.gapic.model.*;
Wildcard import should not be used based on go/java-style#s3.3.1-wildcard-imports

2022-08-25 21:32 UTC, vam-google requested changes
The original got redefined, thus the PR fixing it is expected to be modified to match that. Please see the updated bug description.

2022-11-01 04:30 UTC, blakeli0 commented
The original issue is not valid anymore.

2022-11-01 04:30 UTC, closed without merging