fix(Spring CodeGen): Add user-agent header to generated client for metrics
googleapis/gapic-generator-java pull request #1064
Opened 2022-10-21 21:04 UTC by zhumin8

Adding user-agent header to generated client for metrics. Will mark this ready when header is setup and tested.

Also included some cleanups on un-used code in class (second committish - 04814ef).

2022-10-24 14:16 UTC, elefeint requested changes
Make sure to test that the underlying header provider is also still used (the one that sends Gax/client library versions).

2022-10-26 19:52 UTC, zhumin8 commented
I am still waiting for test metric data to show-up, but in theory, our change should not affect the Gax/client library header provider.
Client library header is set through [`setInternalHeaderProvider()`](https://github.com/googleapis/java-vision/blob/main/google-cloud-vision/src/main/java/com/google/cloud/vision/v1/stub/ImageAnnotatorStubSettings.java#L373) and defined [here](https://github.com/googleapis/java-vision/blob/main/google-cloud-vision/src/main/java/com/google/cloud/vision/v1/stub/ImageAnnotatorStubSettings.java#L220-L226).  However, this `setInternalHeaderProvider()` method is protected in gax, and we are using [`setHeaderProvider()`](https://github.com/googleapis/gax-java/blob/main/gax/src/main/java/com/google/api/gax/rpc/ClientSettings.java#L202) for for custom static headers instead.

2022-11-07 14:56 UTC, zhumin8 commented
Test results with new tool_name: `spring-autogen` aligns with expected.
```
[{
 "service_name": "vision",
 "client_library_type": "gapic",
 "tool_name": "spring-autogen",
 "is_internal": null,
 "obscured_client_project_number": xxxx,
 "f0_": "4"
}, {
 "service_name": "language",
 "client_library_type": "gapic",
 "tool_name": "spring-autogen",
 "is_internal": null,
 "obscured_client_project_number":  xxxx,
 "f0_": "24"
}]
```
Will resolve merging conflicts.

2022-11-10 22:29 UTC, elefeint approved these changes

2022-11-10 23:47 UTC, merged