chore: unpin versions in requirements.in and enable renovate bot
googleapis/gapic-generator-java pull request #1584
Opened 2023-03-29 21:55 UTC by mpeddada1

Related to https://github.com/googleapis/gapic-generator-java/issues/1485

We are currently managing the versions in the requirement.txt file manually (unless [there is a dependabot security update](https://github.com/googleapis/gapic-generator-java/pull/1297)). See https://github.com/googleapis/gapic-generator-java/pull/1370. 

Similar to the changes applied in https://github.com/googleapis/synthtool/pull/1741, now that our jobs have been upgraded to Python 3.9, we no longer have to pin the dependencies in requirement.txt and can start receiving automated updates via renovate-bot.

2023-03-30 14:27 UTC, suztomo requested changes
We don't use java-common-protos/.kokoro. (Let me know if you think otherwise)


Would you add a check (either this PR or another PR) to ensure these requirements files can be installed. It's great if we can use the same container image as we use in the release job.

2023-03-30 14:46 UTC, mpeddada1 commented
> We don't use java-common-protos/.kokoro. (Let me know if you think otherwise)

Not sure if this is expected but I see that the nightly and presubmit jobs are still running but the release jobs haven't been executed since Nov, 2022. Does that mean that the `.kokoro/release` scripts can be removed? 

![Screenshot 2023-03-30 at 10 41 50 AM](https://user-images.githubusercontent.com/66699525/228873509-a7e89537-ccaa-4fe1-a57e-fd8ea8665973.png)

> Would you add a check (either this PR or another PR) to ensure these requirements files can be installed. It's great if we can use the same container image as we use in the release job.

Sure! I'll work on adding the check in.

2023-03-31 13:38 UTC, mpeddada1 commented
@suztomo I've removed the `.kokoro` directory from java-common-protos and added a check for requirements.txt. Could I get another review from you?

2023-03-31 13:58 UTC, suztomo commented on .github/workflows/ci.yaml
> +      - run: python3 -m pip install --require-hashes -r .kokoro/requirements.txt
Great. Can you also add check to confirm `releasetool` module import? 

- https://github.com/googleapis/gapic-generator-java/blob/main/.kokoro/release/stage.sh#LL23C3-L23C25
- https://github.com/googleapis/synthtool/blob/master/docker/owlbot/java/container_test.yaml#L36

2023-03-31 17:57 UTC, suztomo approved these changes
Thank you. Merge once all are green.

2023-03-31 19:18 UTC, merged