[javanaut]feat: Add Logical operation expr and unit test
googleapis/gapic-generator-java pull request #293
Opened 2020-09-10 21:30 UTC by summer-ji-eng

enables logical operators (&&) and (||)

2020-09-11 00:44 UTC, miraleung requested changes

2020-09-11 00:44 UTC, miraleung commented on src/test/java/com/google/api/generator/engine/writer/JavaWriterVisitorTest.java
> +  public void writeLogicalOperationExpr_LogicalAnd() {
Nit: lowercase after "_", e.g. `_logicalAnd`. Same below.

2020-09-11 21:30 UTC, summer-ji-eng commented on src/test/java/com/google/api/generator/engine/writer/JavaWriterVisitorTest.java
> +  public void writeLogicalOperationExpr_LogicalAnd() {
my bad. fixed.

2020-09-12 00:05 UTC, miraleung approved these changes

2020-09-13 08:02 UTC, merged