chore: add codeowners and repo settings
googleapis/gapic-generator-java pull request #312
Opened 2020-09-17 00:17 UTC by JustinBeckwith

2020-09-17 00:43 UTC, miraleung requested changes
Can we make the owners settings narrower for this repo? Since it's in development, let's start with myself, and we can add to that set as more folks become familiar with this codebase.

2020-09-17 03:43 UTC, JustinBeckwith commented
Sure thing!  For which part?  
- For CODEOWNERS right now, actools or yoshi-java can sign off - do you want that to just be you?
- For write/admin access, it's set up kind of standard java.  Do you want to change that bit?

2020-09-17 19:37 UTC, summer-ji-eng commented
> Sure thing! For which part?
> 
> * For CODEOWNERS right now, actools or yoshi-java can sign off - do you want that to just be you?
> * For write/admin access, it's set up kind of standard java.  Do you want to change that bit?

Currently, @miraleung, @summer-ji-eng @xiaozhenliu-gg5 are the main contributors to this repo.

2020-09-18 17:15 UTC, JustinBeckwith commented
I just yanked any team config to reduce confusion.  Feel free to update if/when you like!

2020-09-19 00:06 UTC, summer-ji-eng commented on .github/CODEOWNERS
> +*     @miraleung, @summer-ji-eng @xiaozhenliu-gg5
No need comma here.

2020-09-19 00:07 UTC, summer-ji-eng commented
Thanks @JustinBeckwith helping us on this. LGTM, wait for @miraleung take another look.

2020-09-22 01:54 UTC, JustinBeckwith commented
Thanks!  Ready for another look @miraleung :)

2020-09-23 04:14 UTC, merged