[fix]correct typos
googleapis/gapic-generator-java pull request #492
Opened 2020-11-14 00:36 UTC by summer-ji-eng

2020-11-14 22:49 UTC, miraleung requested changes

2020-11-14 22:49 UTC, miraleung commented on src/main/java/com/google/api/generator/gapic/composer/ResourceNameHelperClassComposer.java
> +            "Cardinality of patterns (%d) and associated variables (%d) do not match for"
The plural form of "Cardinality" was not a typo, let's keep that as-is.

2020-11-16 17:55 UTC, xiaozhenliu-gg5 approved these changes

2020-11-16 21:04 UTC, miraleung approved these changes

2020-11-16 23:11 UTC, merged