[composer][4/5]Implement LRO unary rpc method's sample code
googleapis/gapic-generator-java pull request #514
Opened 2020-11-18 06:05 UTC by summer-ji-eng

2020-11-19 01:12 UTC, miraleung requested changes

2020-11-19 01:12 UTC, miraleung commented on src/main/java/com/google/api/generator/gapic/composer/SampleCodeHelperComposer.java
> +      Method method,
Wasn't this part of the previous PR? Can we make the diffs from base PRs go away, so I can identify what I should be reviewing?

Will review the rest of the code afterwards.

2020-11-20 08:27 UTC, summer-ji-eng commented
Rebased branch rpc_unary_paged_sc_33 and refactor client type to client variable expr.

2020-11-20 09:55 UTC, summer-ji-eng commented on src/main/java/com/google/api/generator/gapic/composer/SampleCodeHelperComposer.java
> +        AssignmentExpr.builder()
TODO: fix consider method.outputType is VOID

2020-11-21 01:38 UTC, miraleung requested changes
Will revisit this and the downstream PRs when the variable re-creation and comment accuracy comments from #512, #513 have been addressed.

2020-11-21 01:38 UTC, miraleung commented on test/integration/goldens/redis/CloudRedisClient.java
> +   *   InputConfig input_config = InputConfig.newBuilder().build();
Let's stick with the lowerCamelCase Java conventions.

2020-11-21 01:38 UTC, miraleung commented on test/integration/goldens/redis/CloudRedisClient.java
> +   *   Operation response = cloudRedisClient.importInstanceAsync(name, input_config).get();
Could we please look for applicable examples where the proto would return empty, and handle those as well?

2020-12-09 07:37 UTC, summer-ji-eng commented
refactor in #587

2020-12-09 07:37 UTC, closed without merging