[composer][5/5]Implement default unary rpc method's sample code
googleapis/gapic-generator-java pull request #517
Opened 2020-11-18 19:47 UTC by summer-ji-eng

Default method generated from [here](https://github.com/googleapis/gapic-generator-java/blob/d3dce0538a527e0214a1a72bc27e8418b0e2905e/src/main/java/com/google/api/generator/gapic/composer/ServiceClientClassComposer.java#L474)

There are 3 kinds sample code for default unary rpc:
1. pure unary rpc's sample code
2. paged unary rpc's sample code
3. lro unary rpc's sample code.

2020-11-19 02:05 UTC, miraleung commented on src/main/java/com/google/api/generator/gapic/composer/SampleCodeHelperComposer.java
>    private static Expr assignMethodArgumentWithDefaultValue(
Can we refactor this so that we use the variable expr throughout (like one would do with Java programming) instead of recreating it several times?

2020-11-19 02:07 UTC, miraleung requested changes

2020-11-19 02:07 UTC, miraleung commented on src/main/java/com/google/api/generator/gapic/composer/SampleCodeHelperComposer.java
> +      // e.g. for (EchoClient echoClient : echoClient.PagedExpand(request).iterateAll()) {//..}
This line looks off, I'm not sure that `iterateAll` on that method would return a list of `echoClient`s.

2020-12-14 07:29 UTC, summer-ji-eng commented
refactor in #594

2020-12-14 07:29 UTC, closed without merging