[WIP]Merge Sample Code  into Master
googleapis/gapic-generator-java pull request #645
Opened 2021-01-21 05:38 UTC by summer-ji-eng

2021-01-22 20:10 UTC, summer-ji-eng commented
Hi @chingor13, we complete the sample code implementation in `gapic-generator-java`. Could you review on the client libraries' sample codes where are generated by this feature before it launch. It locates at `test/integration/goldens` [directory](https://github.com/googleapis/gapic-generator-java/tree/samplecode-master/test/integration/goldens). Please let me know if you have any question. Appreciate any feedback or comment. Thanks a lot. 🙏

2021-01-25 23:17 UTC, miraleung requested changes
Should this wait for #646 and #647?

2021-01-25 23:20 UTC, miraleung requested changes
Could you please run the commands to double-check this as well (shared via chat)?

2021-01-25 23:27 UTC, summer-ji-eng commented
> #646 and #647

@miraleung These two PR is not change the code surface. So it will not be the blocker, but I prefer to wait these RPs.

2021-01-26 19:49 UTC, summer-ji-eng commented
@miraleung @chingor13 Please take another look. After point `third_party/googleapis/WORKSPACE` to the local `gapic-generator-java` 's latest `samplecode-master` branch, All tests passed in `google3/third_party/googleapis` environment.
```
INFO: Elapsed time: 484.255s, Critical Path: 52.84s
INFO: 5294 processes: 835 internal, 3209 linux-sandbox, 1250 worker.
INFO: Build completed successfully, 5294 total actions
//google/ads/admob/v1:com.google.ads.admob.v1.AdMobApiClientTest         PASSED in 1.7s
//google/analytics/admin/v1alpha:admin_go_gapic_test                     PASSED in 0.3s
//google/analytics/data/v1alpha:com.google.analytics.data.v1alpha.AlphaAnalyticsDataClientTest PASSED in 1.2s
//google/api/servicemanagement/v1:com.google.cloud.api.servicemanagement.v1.ServiceManagerClientTest PASSED in 3.0s
//google/area120/tables/v1alpha1:com.google.area120.tables.v1alpha.TablesServiceClientTest PASSED in 2.8s
//google/bigtable/admin/v2:com.google.cloud.bigtable.admin.v2.BaseBigtableInstanceAdminClientTest PASSED in 3.2s
//google/bigtable/admin/v2:com.google.cloud.bigtable.admin.v2.BaseBigtableTableAdminClientTest PASSED in 3.6s
//google/bigtable/v2:com.google.cloud.bigtable.data.v2.BaseBigtableDataClientTest PASSED in 2.8s
//google/chromeos/moblab/v1beta1:com.google.chromeos.moblab.v1beta1.BuildServiceClientTest PASSED in 0.8s
//google/cloud/accessapproval/v1:com.google.cloud.accessapproval.v1.AccessApprovalAdminClientTest PASSED in 0.7s
//google/cloud/aiplatform/v1beta1:com.google.cloud.aiplatform.v1beta1.DatasetServiceClientTest PASSED in 3.5s
//google/cloud/aiplatform/v1beta1:com.google.cloud.aiplatform.v1beta1.EndpointServiceClientTest PASSED in 2.9s
//google/cloud/aiplatform/v1beta1:com.google.cloud.aiplatform.v1beta1.JobServiceClientTest PASSED in 3.7s
//google/cloud/aiplatform/v1beta1:com.google.cloud.aiplatform.v1beta1.MigrationServiceClientTest PASSED in 2.0s
//google/cloud/aiplatform/v1beta1:com.google.cloud.aiplatform.v1beta1.ModelServiceClientTest PASSED in 2.7s
//google/cloud/aiplatform/v1beta1:com.google.cloud.aiplatform.v1beta1.PipelineServiceClientTest PASSED in 2.5s
//google/cloud/aiplatform/v1beta1:com.google.cloud.aiplatform.v1beta1.PredictionServiceClientTest PASSED in 1.7s
//google/cloud/aiplatform/v1beta1:com.google.cloud.aiplatform.v1beta1.SpecialistPoolServiceClientTest PASSED in 1.9s
//google/cloud/asset/v1:com.google.cloud.asset.v1.AssetServiceClientTest PASSED in 3.5s
//google/cloud/asset/v1p1beta1:com.google.cloud.asset.v1p1beta1.AssetServiceClientTest PASSED in 1.9s
//google/cloud/asset/v1p2beta1:com.google.cloud.asset.v1p2beta1.AssetServiceClientTest PASSED in 2.1s
//google/cloud/asset/v1p4beta1:com.google.cloud.asset.v1p4beta1.AssetServiceClientTest PASSED in 2.2s
//google/cloud/asset/v1p5beta1:com.google.cloud.asset.v1p5beta1.AssetServiceClientTest PASSED in 1.8s
//google/cloud/assuredworkloads/v1beta1:com.google.cloud.assuredworkloads.v1beta1.AssuredWorkloadsServiceClientTest PASSED in 2.4s
//google/cloud/automl/v1:com.google.cloud.automl.v1.AutoMlClientTest     PASSED in 3.9s
//google/cloud/automl/v1:com.google.cloud.automl.v1.PredictionServiceClientTest PASSED in 2.5s
//google/cloud/automl/v1beta1:com.google.cloud.automl.v1beta1.AutoMlClientTest PASSED in 4.5s
//google/cloud/automl/v1beta1:com.google.cloud.automl.v1beta1.PredictionServiceClientTest PASSED in 1.8s
//google/cloud/bigquery/connection/v1:com.google.cloud.bigqueryconnection.v1.ConnectionServiceClientTest PASSED in 2.1s
//google/cloud/bigquery/connection/v1beta1:com.google.cloud.bigquery.connection.v1beta1.ConnectionServiceClientTest PASSED in 2.0s
//google/cloud/bigquery/datatransfer/v1:com.google.cloud.bigquery.datatransfer.v1.DataTransferServiceClientTest PASSED in 2.8s
//google/cloud/bigquery/reservation/v1:com.google.cloud.bigquery.reservation.v1.ReservationServiceClientTest PASSED in 2.9s
//google/cloud/bigquery/reservation/v1beta1:com.google.cloud.bigquery.reservation.v1beta1.ReservationServiceClientTest PASSED in 4.5s
//google/cloud/bigquery/storage/v1:com.google.cloud.bigquery.storage.v1.BaseBigQueryReadClientTest PASSED in 2.0s
//google/cloud/bigquery/storage/v1alpha2:com.google.cloud.bigquery.storage.v1alpha2.BigQueryWriteClientTest PASSED in 2.4s
//google/cloud/bigquery/storage/v1beta1:com.google.cloud.bigquery.storage.v1beta1.BaseBigQueryStorageClientTest PASSED in 2.3s
//google/cloud/bigquery/storage/v1beta2:com.google.cloud.bigquery.storage.v1beta2.BaseBigQueryReadClientTest PASSED in 1.8s
//google/cloud/bigquery/v2:com.google.cloud.bigquery.v2.ModelServiceClientTest PASSED in 2.6s
//google/cloud/billing/budgets/v1:com.google.cloud.billing.budgets.v1.BudgetServiceClientTest PASSED in 0.7s
//google/cloud/billing/budgets/v1beta1:com.google.cloud.billing.budgets.v1beta1.BudgetServiceClientTest PASSED in 2.0s
//google/cloud/billing/v1:com.google.cloud.billing.v1.CloudBillingClientTest PASSED in 2.4s
//google/cloud/billing/v1:com.google.cloud.billing.v1.CloudCatalogClientTest PASSED in 2.3s
//google/cloud/channel/v1:com.google.cloud.channel.v1.CloudChannelServiceClientTest PASSED in 3.7s
//google/cloud/datacatalog/v1:com.google.cloud.datacatalog.v1.DataCatalogClientTest PASSED in 4.4s
//google/cloud/datacatalog/v1beta1:com.google.cloud.datacatalog.v1beta1.DataCatalogClientTest PASSED in 2.4s
//google/cloud/datacatalog/v1beta1:com.google.cloud.datacatalog.v1beta1.PolicyTagManagerClientTest PASSED in 2.3s
//google/cloud/datacatalog/v1beta1:com.google.cloud.datacatalog.v1beta1.PolicyTagManagerSerializationClientTest PASSED in 2.0s
//google/cloud/datalabeling/v1beta1:com.google.cloud.datalabeling.v1beta1.DataLabelingServiceClientTest PASSED in 5.4s
//google/cloud/dataproc/v1:com.google.cloud.dataproc.v1.AutoscalingPolicyServiceClientTest PASSED in 2.5s
//google/cloud/dataproc/v1:com.google.cloud.dataproc.v1.ClusterControllerClientTest PASSED in 2.5s
//google/cloud/dataproc/v1:com.google.cloud.dataproc.v1.JobControllerClientTest PASSED in 2.3s
//google/cloud/dataproc/v1:com.google.cloud.dataproc.v1.WorkflowTemplateServiceClientTest PASSED in 2.3s
//google/cloud/dataproc/v1beta2:com.google.cloud.dataproc.v1beta2.AutoscalingPolicyServiceClientTest PASSED in 1.6s
//google/cloud/dataproc/v1beta2:com.google.cloud.dataproc.v1beta2.ClusterControllerClientTest PASSED in 2.4s
//google/cloud/dataproc/v1beta2:com.google.cloud.dataproc.v1beta2.JobControllerClientTest PASSED in 2.4s
//google/cloud/dataproc/v1beta2:com.google.cloud.dataproc.v1beta2.WorkflowTemplateServiceClientTest PASSED in 3.8s
//google/cloud/dataqna/v1alpha:com.google.cloud.dataqna.v1alpha.AutoSuggestionServiceClientTest PASSED in 1.4s
//google/cloud/dataqna/v1alpha:com.google.cloud.dataqna.v1alpha.QuestionServiceClientTest PASSED in 2.3s
//google/cloud/dialogflow/cx/v3:com.google.cloud.dialogflow.cx.v3.AgentsClientTest PASSED in 3.2s
//google/cloud/dialogflow/cx/v3:com.google.cloud.dialogflow.cx.v3.EntityTypesClientTest PASSED in 2.2s
//google/cloud/dialogflow/cx/v3:com.google.cloud.dialogflow.cx.v3.EnvironmentsClientTest PASSED in 2.1s
//google/cloud/dialogflow/cx/v3:com.google.cloud.dialogflow.cx.v3.FlowsClientTest PASSED in 2.8s
//google/cloud/dialogflow/cx/v3:com.google.cloud.dialogflow.cx.v3.IntentsClientTest PASSED in 2.5s
//google/cloud/dialogflow/cx/v3:com.google.cloud.dialogflow.cx.v3.PagesClientTest PASSED in 2.0s
//google/cloud/dialogflow/cx/v3:com.google.cloud.dialogflow.cx.v3.SecuritySettingsServiceClientTest PASSED in 2.0s
//google/cloud/dialogflow/cx/v3:com.google.cloud.dialogflow.cx.v3.SessionEntityTypesClientTest PASSED in 2.1s
//google/cloud/dialogflow/cx/v3:com.google.cloud.dialogflow.cx.v3.SessionsClientTest PASSED in 2.7s
//google/cloud/dialogflow/cx/v3:com.google.cloud.dialogflow.cx.v3.TestCasesClientTest PASSED in 3.2s
//google/cloud/dialogflow/cx/v3:com.google.cloud.dialogflow.cx.v3.TransitionRouteGroupsClientTest PASSED in 2.3s
//google/cloud/dialogflow/cx/v3:com.google.cloud.dialogflow.cx.v3.VersionsClientTest PASSED in 2.3s
//google/cloud/dialogflow/cx/v3:com.googl [...]

2021-01-26 19:58 UTC, miraleung approved these changes
Please wait for chingor@ to approve the generated sample code (under `test/integration/goldens`).

2021-01-28 17:45 UTC, chingor13 approved these changes

2021-01-29 03:34 UTC, Neenu1995 approved these changes

2021-01-29 19:40 UTC, merged