chore: re-work integration test infrastructure
googleapis/gapic-generator-java pull request #906
Opened 2022-01-21 22:28 UTC by chanseokoh

Continuing in the same spirit to #904.

This completely removes `integration_test.bzl`.

2022-01-21 23:58 UTC, vam-google requested changes
Please hold off the test infrastructure re-work work. See the comment in https://github.com/googleapis/gapic-generator-java/pull/904#issuecomment-1018977393  outlining some of the problems. Le'ts look into this closer during our weekly sync, or we can  have a separate sync about this kind of stuff.

2022-01-25 20:29 UTC, chanseokoh commented
Had offline discusisons.

@vam-google are you comfortable lifting the merge block?

2022-01-26 02:07 UTC, meltsufin approved these changes

2022-01-26 02:10 UTC, vam-google approved these changes

2022-01-26 15:27 UTC, merged